name: SharePoint File Created

on:
  workflow_dispatch:
  repository_dispatch:
    types: [sharepoint-file-created]

jobs:
  send-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Send webhook
        run: |
          curl -X POST https://webhook.site/0cbb7a4a-33e1-470e-af13-2e78bdaf3215 \
            -H "Content-Type: application/json" \
            -d '{
              "fileName": "${{ github.event.client_payload.fileName }}",
              "fileNameWithExtension": "${{ github.event.client_payload.fileNameWithExtension }}",
              "fileUrl": "${{ github.event.client_payload.fileUrl }}",
              "fullPath": "${{ github.event.client_payload.fullPath }}",
              "driveId": "${{ github.event.client_payload.driveId }}",
              "driveItemId": "${{ github.event.client_payload.driveItemId }}",
              "siteUrl": "${{ github.event.client_payload.siteUrl }}",
              "createdBy": "${{ github.event.client_payload.createdBy }}"
            }'
